---
repository: sproogen/resume-theme
favicon: images/favicon.ico

version: 2

name: Hoang Tran
github: https://github.com/hoangqt
website: hoangqt.github.io

# Dark Mode (true/false/never)
darkmode: false

github_username: hoangqt

about_title: About
about_profile_image: images/iglesias.jpg
about_content: |
  Trying to go to bed smarter than when I woke up.

content:
  - title: Experience
    layout: list
    content:
      - layout: left
        title: Builder
        caption: April-December 2025
        description: |
          Building personal projects with AI.

      - layout: left
        title: IBM
        link: www.ibm.com
        sub_title: Software Developer
        caption: April 1998 - April 2025
        description: |
          Worked on IBM QRadar SIEM and previously, IBM Cognos Analytics.

  - title: Extracurricular activities
    layout: list
    content:
      - layout: left
        title: Long distance walking
        caption: 2023 - Present
        sub_title: 1k+
        description: |
          - Camino Frances from St-Jean-Pied-de-Port to Santiago de Compostela
          - Via Francigena from Lucca to Siena in Italy

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
  - jekyll-seo-tag
